import type { Theme } from './theme';
import type { CSSProperties } from 'react';

export const globalStyles = (t: Theme): Record<string, CSSProperties> => ({
  body: {
    background: `linear-gradient(165deg, ${t.bg} 0%, ${t.bgMid} 50%, ${t.bg} 100%)`,
    backgroundAttachment: 'fixed',
    color: t.body,
    fontFamily: "'Source Serif 4', Georgia, serif",
    fontWeight: 350,
    fontSize: '17px',
    lineHeight: 1.8,
    margin: 0,
    transition: 'background 0.3s, color 0.3s',
  },
  nav: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '1rem 2rem',
    borderBottom: `1px solid ${t.border}`,
    position: 'sticky' as const,
    top: 0,
    background: `${t.bg}ee`,
    zIndex: 100,
    backdropFilter: 'blur(12px)',
  },
  logo: {
    fontFamily: "'Playfair Display', Georgia, serif",
    fontSize: '1.4rem',
    fontWeight: 700,
    color: t.heading,
    textDecoration: 'none',
  },
  navLinks: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
  },
  navLink: {
    color: t.bodyMuted,
    textDecoration: 'none',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '0.8rem',
    letterSpacing: '0.05em',
    transition: 'color 0.2s',
  },
  navLinkActive: {
    color: t.glowGreen,
  },
  prose: {
    maxWidth: '780px',
    margin: '0 auto',
    padding: '3rem 2rem',
  },
  h1: {
    fontFamily: "'Playfair Display', Georgia, serif",
    fontSize: 'clamp(2rem, 4vw, 3.2rem)',
    fontWeight: 600,
    color: t.heading,
    lineHeight: 1.15,
    marginBottom: '1rem',
  },
  h2: {
    fontFamily: "'Playfair Display', Georgia, serif",
    fontSize: 'clamp(1.4rem, 3vw, 2rem)',
    fontWeight: 600,
    color: t.heading,
    lineHeight: 1.2,
    marginTop: '3rem',
    marginBottom: '1rem',
  },
  h3: {
    fontFamily: "'Playfair Display', Georgia, serif",
    fontSize: '1.2rem',
    fontWeight: 500,
    color: t.heading,
    marginTop: '2rem',
    marginBottom: '0.5rem',
  },
  lead: {
    fontSize: '1.15rem',
    color: t.bodyMuted,
    fontStyle: 'italic',
    marginBottom: '2rem',
  },
  card: {
    background: t.cardBg,
    border: `1px solid ${t.border}`,
    borderRadius: '8px',
    padding: '1.5rem',
    marginBottom: '1.5rem',
  },
  fl: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '0.65rem',
    letterSpacing: '0.2em',
    textTransform: 'uppercase' as const,
    color: t.glowCyan,
    marginBottom: '0.5rem',
  },
  footer: {
    borderTop: `1px solid ${t.border}`,
    padding: '3rem 2rem',
    textAlign: 'center' as const,
    color: t.bodyMuted,
    fontSize: '0.85rem',
  },
  a: {
    color: t.glowGreen,
    textDecoration: 'none',
  },
});
