name: CD - Continuous Deployment

on:
  # push trigger disabled — re-enable when infrastructure is ready
  # push:
  #   branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Build and push Docker images
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service: [api, worker, ui]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_ENDPOINT_STAGING }}

  # Deploy to staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main' || github.event.inputs.environment == 'staging'
    environment:
      name: staging
      url: https://staging.habitat.example.com
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_KEY }}
      
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy to staging server
        env:
          HOST: ${{ secrets.STAGING_HOST }}
          USER: ${{ secrets.STAGING_USER }}
          DEPLOY_PATH: ${{ secrets.STAGING_DEPLOY_PATH }}
        run: |
          ssh $USER@$HOST << 'EOF'
            cd $DEPLOY_PATH
            
            # Pull latest images
            docker compose -f docker-compose.prod.yml pull
            
            # Run database migrations
            docker compose -f docker-compose.prod.yml run --rm api npm run migrate
            
            # Restart services with zero-downtime
            docker compose -f docker-compose.prod.yml up -d --no-deps --build
            
            # Wait for health checks
            sleep 10
            
            # Verify deployment
            docker compose -f docker-compose.prod.yml ps
            
            # Cleanup old images
            docker image prune -f
          EOF
      
      - name: Health check
        run: |
          sleep 30
          curl -f https://staging.habitat.example.com/api/health || exit 1

  # Deploy to production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.event.inputs.environment == 'production'
    environment:
      name: production
      url: https://habitat.example.com
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PRODUCTION_SSH_KEY }}
      
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts
      
      - name: Create backup
        env:
          HOST: ${{ secrets.PRODUCTION_HOST }}
          USER: ${{ secrets.PRODUCTION_USER }}
          DEPLOY_PATH: ${{ secrets.PRODUCTION_DEPLOY_PATH }}
        run: |
          ssh $USER@$HOST << 'EOF'
            cd $DEPLOY_PATH
            
            # Backup database
            docker compose -f docker-compose.prod.yml exec -T postgres \
              pg_dump -U habitat habitat > backup-$(date +%Y%m%d-%H%M%S).sql
            
            # Tag current deployment
            docker tag habitat-api:latest habitat-api:rollback
            docker tag habitat-worker:latest habitat-worker:rollback
            docker tag habitat-ui:latest habitat-ui:rollback
          EOF
      
      - name: Deploy to production server
        env:
          HOST: ${{ secrets.PRODUCTION_HOST }}
          USER: ${{ secrets.PRODUCTION_USER }}
          DEPLOY_PATH: ${{ secrets.PRODUCTION_DEPLOY_PATH }}
        run: |
          ssh $USER@$HOST << 'EOF'
            cd $DEPLOY_PATH
            
            # Pull latest images
            docker compose -f docker-compose.prod.yml pull
            
            # Run database migrations
            docker compose -f docker-compose.prod.yml run --rm api npm run migrate
            
            # Blue-green deployment: scale up new instances
            docker compose -f docker-compose.prod.yml up -d --scale api=2 --scale worker=2 --no-recreate
            
            # Wait for health checks
            sleep 30
            
            # Scale down old instances
            docker compose -f docker-compose.prod.yml up -d --scale api=1 --scale worker=1
            
            # Restart UI
            docker compose -f docker-compose.prod.yml up -d --no-deps ui
            
            # Verify deployment
            docker compose -f docker-compose.prod.yml ps
            
            # Cleanup
            docker image prune -f
          EOF
      
      - name: Health check
        run: |
          sleep 30
          curl -f https://habitat.example.com/api/health || exit 1
      
      - name: Notify deployment
        if: success()
        run: echo "Production deployment successful!"

  # Rollback capability
  rollback:
    name: Rollback
    runs-on: ubuntu-latest
    if: failure() && github.event.inputs.environment == 'production'
    needs: deploy-production
    environment:
      name: production
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PRODUCTION_SSH_KEY }}
      
      - name: Rollback deployment
        env:
          HOST: ${{ secrets.PRODUCTION_HOST }}
          USER: ${{ secrets.PRODUCTION_USER }}
          DEPLOY_PATH: ${{ secrets.PRODUCTION_DEPLOY_PATH }}
        run: |
          ssh $USER@$HOST << 'EOF'
            cd $DEPLOY_PATH
            
            # Restore previous images
            docker tag habitat-api:rollback habitat-api:latest
            docker tag habitat-worker:rollback habitat-worker:latest
            docker tag habitat-ui:rollback habitat-ui:latest
            
            # Restart services
            docker compose -f docker-compose.prod.yml up -d --force-recreate
            
            # Rollback database (if backup exists)
            LATEST_BACKUP=$(ls -t backup-*.sql | head -1)
            if [ -f "$LATEST_BACKUP" ]; then
              docker compose -f docker-compose.prod.yml exec -T postgres \
                psql -U habitat habitat < $LATEST_BACKUP
            fi
          EOF
      
      - name: Notify rollback
        run: echo "Rollback completed!"
